[package]
name = "app"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "app"
path = "main.rs"

[dependencies]
async-nats = {version = "0.33", features = ["service"]}
tokio = { version = "1.20.0", features = ["full"] }
futures = "0.3.21"
serde_json = "1.0.82"
serde = "1.0.139"
rand = "0.8"
